title: <p align="center"> Yogesh Jain </p>
logo: /assets/img/yogesh_jain_image.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/enggyogeshjain/">LinkedIn</a> |
  <a href="https://github.com/enggyog">GitHub</a>
  
  <br>   
  Data Science Manager/Data engineer with 11+ years of experience in IT industry in data Consultancy, data management, ML and time series analytics.
  <br>
  </p>



theme: jekyll-theme-minimal
